### ISSUE TITLE
TDC7201 arduino library

### ISSUE THREAD

**Issue by Francis679** [fedy0/TDC720X#3] opened 2023-11-03 22:10 UTC
I tried implementing this code on an arduino uno board. I am using the TDC7201 evaluation board and generating a clock signal from the analog discovery 2 device (8 MHz). Unfortunately, I cannot initialize the TDC chip via the spi interface, albeit correctly connected. The code does not execute beyond this point.
![Screenshot 2023-11-03 160610](https://github.com/fedy0/TDC720X/assets/71684394/90d7d4bd-f72a-4b3c-9128-8be3e5b50670)
 I keep getting the error message: "Error: TDC2 Initialization failed. Please set at least the CS pin"

**Comment by fedy0** [comment] 2023-11-04 10:31
Can you add a print screen (ie. Serial.println("114");) in [Line 114](https://github.com/fedy0/TDC720X/blob/c2a022979a4ab39873c34a915a4d6260e80593b7/src/TDC720X.cpp#L114) and [Line 119](https://github.com/fedy0/TDC720X/blob/c2a022979a4ab39873c34a915a4d6260e80593b7/src/TDC720X.cpp#L119)? Where does it exit?

Also it seems that the first core was initialized based on your error "Error: **TDC2** Initialization failed. Please set at least the CS pin"

Can I get a clear picture of your setup? (Images, MCU and/or pin connections)

**Comment by Francis679** [comment] 2023-11-05 01:10
![IMG_0151](https://github.com/fedy0/TDC720X/assets/71684394/8dba16ff-3709-4a63-a69b-f18058a54701)
![IMG_0150](https://github.com/fedy0/TDC720X/assets/71684394/044e28fc-fb86-4ae7-81b8-326f4a84a858)
This is the setup showing the connection between the arduino board and 7201 evaluation board

**Comment by fedy0** [comment] 2023-11-06 18:57
I can't see the pins. List the connections
Eg.

TDC CS -> UNO D5 
TDC DIN -> UNO D6
...
etc

Also you didn't answer the question completely in the last comment. What's the print out? I want to know where the function exited

The library was built and tested for Pro mini and esp32. Porting it to Uno shouldn't be a problem

**Comment by Francis679** [comment] 2023-11-06 20:21
sorry my bad.
tdc1 cs >>>> uno 10
tdc2 cs >>>> uno 8
tdc1 interrupt >>uno 2
tdc2 interrupt >> uno 3
tdc enable >>>>uno 4
tdc1 start >>>> uno 7
tdc1 stop >>>> uno 5
tdc2 start >>>> uno 6
tdc2 stop >>>> uno 9
MOSI >>>> uno 11
MISO >>>> uno 12
Serial clock >>> uno >>> 13  
I was running the code i adapted from your (examples folder) "TDC7201.ino". I didn't run the TDC7201.cpp file.

**Comment by fedy0** [comment] 2023-11-07 05:55
> Can you add a print screen (ie. Serial.println("114");) in [Line 114](https://github.com/fedy0/TDC720X/blob/c2a022979a4ab39873c34a915a4d6260e80593b7/src/TDC720X.cpp#L114) and [Line 119](https://github.com/fedy0/TDC720X/blob/c2a022979a4ab39873c34a915a4d6260e80593b7/src/TDC720X.cpp#L119)? Where does it exit?
> 
> Also it seems that the first core was initialized based on your error "Error: **TDC2** Initialization failed. Please set at least the CS pin"
> 
> Can I get a clear picture of your setup? (Images, MCU and/or pin connections)




You've not answered my question yet. How do I help you if I don't know where the function returns? Please add a serial print in the code line numbers I have referenced above

**Comment by Francis679** [comment] 2023-11-07 17:30
sorry i misunderstood you before. take a look at the screenshot of the result i printed after editing lines 114 and 119
![image](https://github.com/fedy0/TDC720X/assets/71684394/38d732e8-1e52-4e05-b3e4-be905965ed63)

**Comment by fedy0** [comment] 2023-11-08 21:48
I think you need to initialize the SPI settings in your code. If you're using the examples directly without modification then you need to also confirm that the default SPI settings of UNO matches the TDC SPI requirements. Also Insert the appropriate CS and EN pins in TDC.begin().

If you share your modified code I may help you debug.

**Comment by Francis679** [comment] 2023-11-08 23:24
Thank you very much for your help.
here's the codes i modified for the uno board:
[tdc7201.txt](https://github.com/fedy0/TDC720X/files/13302234/tdc7201.txt)
[tdc7201_v2.txt](https://github.com/fedy0/TDC720X/files/13302238/tdc7201_v2.txt)

I have tested the codes but unfortunately, i can't initialize the tdc. Thank you

**Comment by fedy0** [comment] 2023-11-11 12:46
Have you tried using ESP32 or Arduino Pro Mini? The library has been tested with these MCUs.

As I do not have an Arduino Uno to test your program it's quite difficult to tell what the problem is. From the code you shared, everything looks good as far as I can see. 

Another place to look out for errors is in the recommended external capacitor and external clock source which must be the same as specified in the TDC Object creation

**Comment by Francis679** [comment] 2023-11-11 13:03
I don't have the esp32 or Pro Mini but I might just buy one. Could you please tell me the exact board you used? Because I'm seeing several variations of the esp32 board and the pin numbers do not tally with the ones in your code. The chip I have is mounted on the evaluation board (provided by TI) so the external capacitor is in place. I just need to supply the external signals required to initialize the chip and measure. Thank you

**Comment by fedy0** [comment] 2023-11-11 13:13
I have used the standard ESP32 nodeMCU. If, you have any problem with any esp32 board. Just let me know. Pinouts shouldn't be a serious problem. I strongly believe that the problem with your current setup maybe from the external clock

**Comment by Francis679** [comment] 2023-11-11 13:17
Thank you. Currently, I'm supplying an 8MHz clock from an analog discovery 2 device. I will continue to troubleshoot. I'll provide feedback. Thanks

**Comment by dingshou11** [comment] 2023-11-25 12:48
If my start and stop pins are connected, how do I input my start and stop signals? Use oscilloscope or directly use esp32 to generate pwm signal.

**Comment by dingshou11** [comment] 2023-11-25 14:40
I successfully run the TDC7200 test code on esp32, but my serial assistant does not output anything, do I need to input something, time_between_pulses_in_us do I need to input it myself? I'm sorry, but I just got involved recently, and there's a lot I don't understand.

**Comment by dingshou11** [comment] 2023-11-25 17:13
Please ignore my question above.I had the same problem with the tdc7200 with the esp32 as the guy above.
![2ADB30D3B5A7AEC030F2844D43D9432E](https://github.com/fedy0/TDC720X/assets/150651065/e7b899d4-24da-47cc-ae3e-4e3afad6d7d5)
![B2D3770E8F76A0C42853A8F441B4D71E](https://github.com/fedy0/TDC720X/assets/150651065/c2d7caca-21e8-45d4-9668-6451fe086da7)
![EA87E9B0B98C985267E559DDAF1791C4](https://github.com/fedy0/TDC720X/assets/150651065/a40f6be9-d715-4655-8394-2f1983377b02)
![QQ截图20231126010612](https://github.com/fedy0/TDC720X/assets/150651065/a10e3616-e99c-45d9-8e34-3b81acfa3714)
"TDC Initialization failed. Please set at least the CS pin"I thought the cs pin (5) should be low active, but I measured it as high.I thought the cs pin (5) should be low active, but I measured it as high. And this code cannot modify the level. pinMode(EXAMPLE_SPI_CS_PIN, OUTPUT); digitalWrite(EXAMPLE_SPI_CS_PIN, LOW);

**Comment by dingshou11** [comment] 2023-11-25 23:27
![image](https://github.com/fedy0/TDC720X/assets/150651065/1ddc2d78-63a5-4264-bbef-e438f3d56921)
![image](https://github.com/fedy0/TDC720X/assets/150651065/a1652ada-a747-40bc-994c-53c2cc4ae807)
I think the code gets bogged down in the setup function, and I only annotated the mini pro pre-defined.

**Comment by dingshou11** [comment] 2023-11-26 00:58
![image](https://github.com/fedy0/TDC720X/assets/150651065/b2db42b2-59d2-4f1f-aa8c-97bebe9028e4)
![image](https://github.com/fedy0/TDC720X/assets/150651065/46476781-a6bf-43fc-90b5-6248a265c978)
I found a problem that the order of the connection diagram was different from that in the chip manual of TDC7200. Instead of following the order, I determined the connection with each other.

**Comment by fedy0** [comment] 2023-11-27 10:05
Please could you highlight in a simple term what problem you're facing as you commented on a lot of things?@dingshou11 

Also what is your clock source?

**Comment by dingshou11** [comment] 2023-11-27 10:45
@fedy0 My clock source is: ESP32: LEDC Peripheral is used for an 8MHz external clock source on GPIO 25.The problem is that the code is stuck in an endless loop in setup. I put in this if statement.Thank you for your reply, you can @me anytime.
![image](https://github.com/fedy0/TDC720X/assets/150651065/5c5a7df5-be4a-4125-b24d-95510bcd151e)

**Comment by fedy0** [comment] 2023-11-27 11:09
Could you download and try it again? I just updated the `./src`

**Comment by dingshou11** [comment] 2023-11-27 11:22
![image](https://github.com/fedy0/TDC720X/assets/150651065/6f505272-e9fe-45d6-ae1d-219596415d27)
I only commented this code, nothing else changed. I changed./src and the problem still appears.

**Comment by fedy0** [comment] 2023-11-27 11:28
I meant, could you download the library again and test?

**Comment by dingshou11** [comment] 2023-11-27 11:30
![image](https://github.com/fedy0/TDC720X/assets/150651065/b7014922-8ca5-4ed2-98e1-25547b57df1c)
Sorry, I didn't make myself clear, but I've updated the library.

**Comment by fedy0** [comment] 2023-11-27 11:39
For the esp32
I think the connection of MISO and MOSI is swapped in the example documentation. Please update it to 

DOUT 19

DIN 23

else

Initialize SPI as follows

SPI.begin(SCLK, MISO, MOSI, SS); // Replace with preferred pinout

Please give feedback @dingshou11 @Francis679 
Also a decoupling capacitor must be placed very close to VREG and of the **ceramic** type and value between 0.4uF - 2.2uF (1uF typical) according to the datasheet

**Comment by dingshou11** [comment] 2023-11-27 11:51
![image](https://github.com/fedy0/TDC720X/assets/150651065/2b0c5be4-6994-49f7-b756-9cb41aff9cd6)
![image](https://github.com/fedy0/TDC720X/assets/150651065/1781f06e-f23a-49ca-8278-70bd18a2e658)
I don't know if I did the right thing. I also changed the connection between tdcc7200 and esp32.

**Comment by fedy0** [comment] 2023-11-27 12:02
Did it work?

I do not have my test circuit with me. But by the end of the week. 

The major sources of problem are
- dirty or unstable clock source
- a very close decoupling capacitor (ceramic 1uF)
- and maybe a poor connection and long connection

As this is a very sensitive circuit, everything matters 

I've tested the library on esp32 and pro and it works.
![Screenshot_2023-11-27-13-01-21-559_com.miui.gallery-edit.jpg](https://github.com/fedy0/TDC720X/assets/26013847/05c04326-4d47-44be-b087-3c9cd56be725)

**Comment by dingshou11** [comment] 2023-11-27 12:16
Sorry, it still doesn't run properly and stopped during the setup phase.I would like to ask a question, is pin 5 of your ESP32 low or high level.Thank you very much. If I have questions, I hope to continue seeking advice.

**Comment by dingshou11** [comment] 2023-12-03 02:42
![image](https://github.com/fedy0/TDC720X/assets/150651065/6f34df00-dbe5-4776-9bc3-db8695e0db07)
@fedy0 @Francis679 Excuse me, have you tried again? I still get an error.
![image](https://github.com/fedy0/TDC720X/assets/150651065/2fd53706-83db-4941-bb7a-8d5ead52e78c)
This is the pin connection diagram of my esp32 and tdc7200.

**Comment by fedy0** [comment] 2023-12-03 20:28
Try [this](https://github.com/Yveaux/TDC7200) let me know your findings @dingshou11

**Comment by dingshou11** [comment] 2023-12-04 04:21
@fedy0 But I have a question, I use esp32, does this code also work?

**Comment by dingshou11** [comment] 2023-12-04 05:49
.h和.cpp文件报错。
![image](https://github.com/fedy0/TDC720X/assets/150651065/f76bd708-9b99-4bd1-b495-1062d69dda59)

**Comment by Francis679** [comment] 2023-12-04 16:48
> ![image](https://private-user-images.githubusercontent.com/150651065/287493895-6f34df00-dbe5-4776-9bc3-db8695e0db07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDc5ODcsIm5iZiI6MTcwMTcwNzY4NywicGF0aCI6Ii8xNTA2NTEwNjUvMjg3NDkzODk1LTZmMzRkZjAwLWRiZTUtNDc3Ni05YmMzLWRiODY5NWUwZGIwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxNjM0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTFhNzZlZmUwZTlmMmUwNWExMzViOTA3MDFmZGUyNDgwMzZkZTM5MTRiNWJiNDE4NTIwMWM3ZDRmMmExYTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uK17SXddiY2_7IeQXhLB869gXbI2cwN3q8pHMzvkFCI) @fedy0 @Francis679 Excuse me, have you tried again? I still get an error. ![image](https://private-user-images.githubusercontent.com/150651065/287493985-2fd53706-83db-4941-bb7a-8d5ead52e78c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDc5ODcsIm5iZiI6MTcwMTcwNzY4NywicGF0aCI6Ii8xNTA2NTEwNjUvMjg3NDkzOTg1LTJmZDUzNzA2LTgzZGItNDk0MS1iYjdhLThkNWVhZDUyZTc4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxNjM0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjllMTg2YzM2MWQ0MTM1ZmIxYjFkZjFhMjE3ODdjMTM2NGJmYzE1MTRjYmEyMzdlM2Y5YjFkNWJiZDE3OGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qO26ttl43XktoCaqy9PG4IsvGnkreHe55kfCRt0K7mc) This is the pin connection diagram of my esp32 and tdc7200.

Hi, I still could not initialize the TDC with this code even with the new esp32 I'm using now. However, I've been able to write the TDC registers directly without using the code (and header file) provided here. I just tried it to be sure my connections are okay and the chip is good too. I will look at it later because I'm currently working on other stuff now. Thank you

**Comment by fedy0** [comment] 2023-12-04 19:36
Can you comment on the bug? I mean what is different from this library. At least to support @dingshou11 needs now

I've been busy recently. I haven't had time to set up the test on my workbench. But I'm still surprised why it's not working for you. Maybe my last few commits messed things up

**Comment by Francis679** [comment] 2023-12-04 19:54
[New Text Document.txt](https://github.com/fedy0/TDC720X/files/13550719/New.Text.Document.txt)
here we just tried to talk to directly to the chip without going through the library. This is to confirm if our connections and chip were working fine. after my exams, i'll try your setup again. I'll be glad to see your setup anytime you can. thank you

**Comment by dingshou11** [comment] 2023-12-05 01:14
@fedy0 Thank you very much. You can take care of your own business first.
@Francis679 I'll try your code in a minute, thank you very much.

**Comment by dingshou11** [comment] 2023-12-05 01:50
![image](https://github.com/fedy0/TDC720X/assets/150651065/520fcc2d-89e6-4d93-99f4-d5703bbe72eb)
@Francis679 I updated my pin connection, I tried your code, I don't know if this is correct.
![image](https://github.com/fedy0/TDC720X/assets/150651065/9b901367-7810-43d9-9f99-b7a90700d3d8)
I did not connect the pin of this device 2, I do not understand why there are two cs pins.

**Comment by Francis679** [comment] 2023-12-05 01:55
> correct.
> ![image](https://private-user-images.githubusercontent.com/150651065/287891515-9b901367-7810-43d9-9f99-b7a90700d3d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDE0NDksIm5iZiI6MTcwMTc0MTE0OSwicGF0aCI6Ii8xNTA2NTEwNjUvMjg3ODkxNTE1LTliOTAxMzY3LTc4MTAtNDNkOS05Zjk5LWI3YTkwNzAwZDNkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwMTUyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzQxZjhkMDM4NTY5YmNiMmFkY2U1YWQ2YzY0NGRlNzIwZjcxY2RlMTRiZWFiYjE4YTEyNjllZjg2MjM2MjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ckOfyscMIs8XTDy0lRcSQZY6gDgaKXjRRXR_oWT_tOY)
> I did not connect the pin of this device 2, I do

I’m using the 7201 chip (which has two tdcs within) . Each of the tdcs have their different CS pins. Please note that this code does not measure TOF or any calibrated tdc measurement. It’s just to ensure that I can talk to the tdc registers via arduino. Thank you

**Comment by dingshou11** [comment] 2023-12-05 02:07
So according to the serial print, have I successfully communicated between the two?
![image](https://github.com/fedy0/TDC720X/assets/150651065/06951a22-a55f-4b48-a807-f6dd2e2609d8)

**Comment by Francis679** [comment] 2023-12-05 04:45
Yeah. Next is to communicate with it via the library provided by @fedy0 .

**Comment by fedy0** [comment] 2023-12-06 16:46
@Francis679 @dingshou11 Could you test it again? 
I suspect that your gcc setup (whether arduino or esp-idf) is using -std=c++11 while I built and tested this library in -std=c++17. 
Please let me know if the update fixed your problem

**Comment by dingshou11** [comment] 2023-12-07 08:11
Sorry, the TDC still cannot be initialized after the update.
![image](https://github.com/fedy0/TDC720X/assets/150651065/a19551fc-b0a8-41aa-b599-76ffaf18f9b5)
![GEB{GLX`A9B_S1YL5 RY3CO](https://github.com/fedy0/TDC720X/assets/150651065/757eea4b-26e6-4a4b-b87a-03debf6595c1)
if I change the "if" statement, I get an error. I would like to know how you can provide the 8Mhz clock frequency.I doubt the esp32 analog ledc peripherals will deliver 8Mhz.

**Comment by dingshou11** [comment] 2023-12-07 10:02
![381E381E7E4A1DAF3872774B66D2E696](https://github.com/fedy0/TDC720X/assets/150651065/cc0908e4-eaee-4571-825c-ee039a4daaa0)
Now I have adjusted your code again, I still doubt that esp32 in the code can not provide 8Mhz clock, I use the oscilloscope to try to measure the 25-pin clock frequency, only 2Mhz can be output.

**Comment by fedy0** [comment] 2023-12-07 14:58
![IMG_20231207_155752.jpg](https://github.com/fedy0/TDC720X/assets/26013847/aa82a3f8-9bf9-48e5-b62f-04a71bdda6c0)

Use these settings in the clock input 
Or try an external clock source.

Note: @dingshou11 changing the frequency source requires that you change the clock in the object declaration

TDC720X TDC(TDC7200, LEDC_FREQUENCY);

@Francis679 Did the update work

**Comment by dingshou11** [comment] 2023-12-08 02:43
@fedy0 The adjustment did output an 8Mhz clock, but it still failed to initialize.
![image](https://github.com/fedy0/TDC720X/assets/150651065/103329bd-c088-4ea1-b4aa-8d8eb2513b1f)
![image](https://github.com/fedy0/TDC720X/assets/150651065/5fc4e19a-cb04-43ba-b3ad-3eb29a0a2ff9)
Is there a problem with the logic of these two pieces of code?
SPI.begin();→cs（GPIO 5）LOW→return false→Enter if, infinite delay

**Comment by fedy0** [comment] 2023-12-08 07:27
There isn't any problem.
I'll work on this library and test it this weekend. I hope you'll be a little patient

**Comment by dingshou11** [comment] 2023-12-08 07:57
Sorry to bother you, I just wanted to get back to you as soon as possible.Hope your work goes well!

**Comment by dingshou11** [comment] 2023-12-11 04:19
@fedy0 After I rearranged the capacitor, I am now successfully initialized. However, there seems to be a problem with the program, which does not work properly after 134 lines.interrupt_flag does not appear to be assigned to 1, indicating a termination failure.
![image](https://github.com/fedy0/TDC720X/assets/150651065/a705a984-c495-4439-bbf8-b524afcaa131)

**Comment by fedy0** [comment] 2023-12-11 17:56
I'm glad it works for you now.

Did you modify the library any further to get it to work?

About the TDC example program, honestly it is not the best way to test the TDC. I hope to improve on the examples. Could you use external triggers to test it?

@Francis679 Does it work for you now?

**Comment by dingshou11** [comment] 2023-12-12 02:31
I didn't make any changes. I have an oscilloscope, can I use an oscilloscope to trigger it externally?However, the interrupt_flag in the program does not return to 1, and the program does not interrupt.

**Comment by dingshou11** [comment] 2023-12-18 16:12
![IFK~7IF7O3$0@5SNTH0VS{R](https://github.com/fedy0/TDC720X/assets/150651065/8fba3dab-fad4-4b6f-afca-4e92edc37d52)
@fedy0 @Francis679 Have you tested it recently? Why hasn't this termination flag been set to 1? I printed it through the serial port and the value has been consistently 0. Causing the program to be unable to continue running while.

**Comment by fedy0** [comment] 2023-12-19 19:13
@dingshou11 could you set and read the values of different registers to be sure the counter triggers are active and triggered. Especially registers TDCx_INT_STATUS and TDCx_INT_MASK

**Comment by zhengiliek** [comment] 2024-08-06 13:37
你好，我直接下载代码后，根据代码上方的连接到tdc7200串口打印如下，正常吗
![DZPA7N7G5_NO%QYS}I1S_WB](https://github.com/user-attachments/assets/ff6a2e7a-9284-419f-b463-1bc9c8a8ae97)

**Comment by fedy0** [comment] 2024-08-07 08:24
@zhengiliek as a quick test see if you can read the default values of the registers CONFIG2 & INIT_MASK

**Comment by fedy0** [comment] 2024-09-06 20:13
@zhengiliek You can open another issue if you have any

**Closed as completed by fedy0** 2024-09-06 20:13 UTC
